import { NextRequest, NextResponse } from "next/server";
import { getAllProjects, getProject } from "@/lib/automation";
import { autoGenerateDeliverables } from "@/lib/delivery";

export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { projectId, password, generateAll } = body;

    // Simple auth
    if (password !== process.env.NEXT_PUBLIC_ADMIN_PASSWORD && password !== "n01admin2024") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const results: { projectId: string; success: boolean; error?: string }[] = [];

    if (generateAll) {
      // Generate for all delivered projects without deliverables
      const projects = await getAllProjects();
      const eligibleProjects = projects.filter(
        p => (p.status === "delivered" || p.status === "completed") && 
             (!p.vercelUrl || !p.githubRepo)
      );

      console.log(`Generating deliverables for ${eligibleProjects.length} projects...`);

      for (const project of eligibleProjects) {
        try {
          const success = await autoGenerateDeliverables(project.id);
          results.push({ projectId: project.id, success });
        } catch (err) {
          results.push({ 
            projectId: project.id, 
            success: false, 
            error: err instanceof Error ? err.message : "Unknown error" 
          });
        }
      }

      return NextResponse.json({
        success: true,
        message: `Processed ${results.length} projects`,
        results,
      });
    }

    // Generate for single project
    if (!projectId) {
      return NextResponse.json({ error: "Project ID required" }, { status: 400 });
    }

    const project = await getProject(projectId);
    if (!project) {
      return NextResponse.json({ error: "Project not found" }, { status: 404 });
    }

    const success = await autoGenerateDeliverables(projectId);

    return NextResponse.json({
      success,
      projectId,
      message: success ? "Deliverables generated!" : "Failed to generate deliverables",
    });

  } catch (error) {
    console.error("Generate deliverables error:", error);
    return NextResponse.json({ 
      error: "Failed to generate deliverables",
      details: error instanceof Error ? error.message : "Unknown error"
    }, { status: 500 });
  }
}

// GET - Check which projects need deliverables
export async function GET(request: NextRequest) {
  const { searchParams } = new URL(request.url);
  const password = searchParams.get("password");

  if (password !== process.env.NEXT_PUBLIC_ADMIN_PASSWORD && password !== "n01admin2024") {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const projects = await getAllProjects();
  
  const needsDeliverables = projects.filter(
    p => (p.status === "delivered" || p.status === "completed") && 
         (!p.vercelUrl || !p.githubRepo)
  );

  const hasDeliverables = projects.filter(
    p => p.vercelUrl && p.githubRepo
  );

  return NextResponse.json({
    summary: {
      total: projects.length,
      needsDeliverables: needsDeliverables.length,
      hasDeliverables: hasDeliverables.length,
    },
    needsDeliverables: needsDeliverables.map(p => ({
      id: p.id,
      name: p.name,
      status: p.status,
      clientEmail: p.clientEmail,
    })),
    hasDeliverables: hasDeliverables.map(p => ({
      id: p.id,
      name: p.name,
      vercelUrl: p.vercelUrl,
      githubRepo: p.githubRepo,
    })),
  });
}
